env:
    es2021: true
    jest/globals: true
    node: true
extends: eslint:recommended
parserOptions:
    ecmaVersion: 13
    sourceType: module
plugins:
    - "prettier"
rules:
    prettier/prettier:
        - error
    linebreak-style:
        - error
        - unix
