arrowParens: "avoid"
bracketSpacing: true
endOfLine: "lf"
htmlWhitespaceSensitivity: "css"
jsxSingleQuote: false
printWidth: 80
proseWrap: "preserve"
quoteProps: "as-needed"
semi: true
singleQuote: false
tabWidth: 4
trailingComma: "all"
useTabs: false
